[tool.poetry]
name = "distribution_optimization_py"
version = "0.1.0"
description = ""
authors = ["WojtAcht <wachtelik@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^1.26.3"
scipy = "^1.11.4"


[tool.poetry.group.dev.dependencies]
pandas = "^2.1.4"
ipykernel = "^6.29.0"



[tool.poetry.group.hmspy.dependencies]
leap-ec = "0.7.0"
cma = "^3.3.0"
treelib = "^1.7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
